---
title: D.C. Car Crash Analysis
author: Justin Schulberg, 
date: '2024-01-16'
slug: dc-car-crashes
categories:
  - EDA
  - clustering
tags:
  - Python
comments: yes
featured_image: ''
share: yes
draft: false
description: "Analysis of transportation-related crashes (car, motorcycle, pedestrian, bike) in the Washington, D.C. area. This project is in-line with D.C.'s Vision Zero goal. This project was completed with a group of students for Georgia Tech's [CSE 6242 Data and Visual Analtytics](https://omscs.gatech.edu/cse-6242-data-visual-analytics)."
---


## Problem Definition
Every year, car accidents are always among the top causes of death in Washington, D.C. In response, the city has launched its [Vision Zero Initiative](https://ddot.dc.gov/page/vision-zero-initiative), an effort to reduce vehicle-related crashes to zero by 2024. The team will determine the root causes of car accidents in Washington, D.C. by analyzing patterns, seasonality, and trends in the data collected from the [Vision Zero website](https://www.dcvisionzero.com/maps-data) and other sources. Our goal is to create an interactive and robust visualization dashboard to communicate the true impact of traffic-related crashes in Washington, D.C. to stakeholders who would be most interested in D.C.’s Vision Zero plan, such as policymakers, police, and local residents.
<br>
## Expected Innovation
Although D.C.’s Vision Zero website includes numerous data visualizations and analytical products, they
lack the following features, that we aim to improve upon:
- **Disjointed Visualizations** - Even though all of the visualizations are built in Tableau and portray
insightful information, they are not connected in one seamless dashboard, allowing users to see
relationships across multiple features at once.
- **Disparate Tools Used** - Currently, the Vision Zero Team creates its visualization products in both
Tableau and ArcGIS. This allows for more powerful mapping capabilities in ArcGIS; however, the
two products are kept separately, making it difficult to understand the relevance of the
geospatial data in the context of other visualizations.
- **Lack of Diversity in Datasets Used** -  Currently, only data on direct crashes are being used.
- **Insufficient Incorporation of Geographic Analysis** - While the current data is mapped, there is
substantial room for additional spatial analysis of existing crash data.
<br>
To build upon this, we will not only integrate multiple data sources, but we will centralize all the data and corresponding visualizations into Tableau. Because we will only be using Tableau, and it offers free licenses to those with University emails, the cost of this project is $0 (Q7). Additionally, we will use time-series modeling to project traffic-related crashes into the future. Lastly, the team plans to integrate not only crash/fatality data, but also demographic, socio-economic, and land use data such as the location of new road infrastructure.
<br>

## Intended Impact
We will integrate multiple data sources to see how different road calming measures (raised surfaces, slowed speed limits, etc.) affect crash frequency before/after implementation. If this effort, or other efforts like it, are unable to find effective methods of crash mitigation, more lives will continue to be at stake. Potential risks exist in the methods for pulling the data and also in joining data. For example, joining crash data, which occurs at a specific location, to road calming efforts, which usually occur in a broader area. 

<br>

For this effort to be successful, we will adhere to the aforementioned Plan of Activities and drive towards effective data integration of our various data sources, modeling of the data that provides meaningful insight into future trends, and development of our interactive dashboard. Success of this project will contribute to the success of D.C.’s goal of zero crash-related fatalities by 2024 in which the D.C. government will measure by the end of 2014.


```{r fig.align='center', fig.height=6, fig.width=6, message=FALSE, warning=FALSE, include=FALSE}
# Set our plot and code block specifications for the rest of the document.
knitr::opts_chunk$set(fig.width = 9,
                      fig.height = 6,
                      fig.align = "center",
                      # Set our code specifications for the rest of the document
                      echo = F,
                      warning = F,
                      message = F)

# Turn off scientific notation
options(scipen=999)

# install.packages("pacman")
# Use pacman to load packages. This'll check to see if a package is already installed; if not, it'll install it. If it is installed, it'll run the library() function.
library(pacman)
pacman::p_load(
  readxl, # Used for reading in Excel packages
  tidyverse, # Used for easy data manipulation
  here, # Used for navigating project structures
  kableExtra, # Used for RMarkdown formatting
  DataExplorer, # Used for easy EDA
  corrplot, # Used for correlation plotting
  forcats, # Used for ordering ggplot variables
  ggplot2, # Used for plotting
  gridExtra, # Used for side-by-side plotting
  # reticulate, # Used for Python programming
  pander # Pretty printing
  )


# Set our ggplot formats so we don't have to re-type the same code over-and-over again.
theme_set(theme_classic())
theme_update(plot.title = element_text(hjust = 0, color = "slateblue4", size = 20),
  plot.subtitle = element_text(hjust = 0, color = "slateblue2", size = 12),
  plot.caption = element_text(color = "dark gray", size = 10, face = "italic"),
  axis.title.x = element_text(size = 14),
  axis.title.y = element_text(size = 14),
  axis.text.y = element_text(size = 10),
  axis.text.x = element_text(size = 10))

```